#!/bin/bash

URL="https://github.com/epasveer/seer"

latest=$(curl -sSL "$URL" | grep -oEi "/releases/tag/v([0-9.]+)" | awk -F '/v' '{print $2}')

latest_file="seer-$latest.tar.gz"
if [ ! -e "$latest_file" ]; then
	latest_url="$URL/archive/refs/tags/v$latest.tar.gz"
	curl -SL "$latest_url" -o "$latest_file"
fi

TOP_DIR=$(readlink -f "seer-$latest")

if [ ! -e "$TOP_DIR" ]; then
	tar -xv --file $latest_file
fi

for dep in cmake qtbase5-dev libqt5charts5-dev; do
	if dpkg-query -W -f='${Status}' $dep | grep -q installed ; then
		echo "$dep installed"
	else
		echo "$dep not installed"
		sudo apt install $dep
	fi
done

cd "$TOP_DIR"/src/build
cmake ..
make seer

cd "$TOP_DIR"

DEB_DIR="$TOP_DIR"/seer_"$latest"_amd64

rm -rf "$DEB_DIR"

mkdir -p "$DEB_DIR"/usr/bin
install -s -m 755 src/build/seer "$DEB_DIR"/usr/bin

mkdir -p "$DEB_DIR"/usr/share/doc/seer
install -m 644 README.md LICENSE "$DEB_DIR"/usr/share/doc/seer

mkdir -p "$DEB_DIR"/usr/share/applications
cat << EOF > "$DEB_DIR"/usr/share/applications/seer.desktop
[Desktop Entry]
Name=Seer
GenericName=Debugger
Comment=GUI frontend to gdb.
Exec=seer
Icon=seer
Terminal=false
Type=Application
Categories=Development;
EOF

for size in 32 64 128 256 512; do
	mkdir -p "$DEB_DIR"/usr/share/icons/hicolor/"$size"x"$size"/apps
	install -m 644 src/resources/seer_"$size"x"$size".png "$DEB_DIR"/usr/share/icons/hicolor/"$size"x"$size"/apps/seer.png
done

deps_file="/dev/shm/seer-deps.txt"
rm -f "$deps_file"
touch "$deps_file"
ldd src/build/seer | while read -r line; do
	if [[ $line == *" => "* ]]; then
		lib=$(echo $line | cut -d' ' -f 1)
		package_info=$(dpkg-query -S $lib)
		package=$(echo $package_info | cut -d':' -f 1)
		echo $package >> "$deps_file"
	fi
done
deps=$(sort -u "$deps_file" | paste -sd ',')
rm -f "$deps_file"

mkdir -p "$DEB_DIR"/DEBIAN
cat << EOF > "$DEB_DIR"/DEBIAN/control
Package: seer
Version: $latest
Section: devel
Priority: optional
Maintainer: H. Turgut Uyar <uyar@tekir.org>
Homepage: https://github.com/epasveer/seer
Architecture: amd64
Depends: gdb,$deps
Description: A GUI frontend to gdb.
EOF

dpkg-deb --build --root-owner-group "$DEB_DIR"
